services:
  - type: web
    name: gpc-itarsi-mongodb-backend
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://gpc-itarsi-9cl7.onrender.com
      - key: MONGODB_URI
        value: mongodb+srv://GPC:anmol4328@gpc-itarsi.puza0ta.mongodb.net/gpc-itarsi
      - key: CLOUDINARY_CLOUD_NAME
        value: daf99zwr2
      - key: CLOUDINARY_API_KEY
        value: 913341861574171
      - key: CLOUDINARY_API_SECRET
        value: qTADLCaw8FaI6HwrC4tLdgpObrU
      - key: CLOUDINARY_URL
        value: cloudinary://913341861574171:qTADLCaw8FaI6HwrC4tLdgpObrU@daf99zwr2
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
